In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./data/ads.csv")
df.head()

    User ID  Age  EstimatedSalary  Purchased
0  15624510   19            19000          0
1  15810944   35            20000          0
2  15668575   26            43000          0
3  15603246   27            57000          0
4  15804002   19            76000          0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB

In [4]:
# remove 'User ID' column

df = df.drop(columns=['User ID'])
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
# performing binning

df['age_category'] = pd.cut(df['Age'], bins=[17, 28, 45, 60], labels=['Youth', 'Mid-age', 'Adult'])        # typical python behaviour for inclusion-exclusion.

df.head()

   Age  EstimatedSalary  Purchased age_category
0   19            19000          0        Youth
1   35            20000          0      Mid-age
2   26            43000          0        Youth
3   27            57000          0        Youth
4   19            76000          0        Youth

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
 3   age_category     400 non-null    category
dtypes: category(1), int64(3)
memory usage: 9.9 KB

In [8]:
# Standarization - Standard Scalar

df['Age'] = ((df['Age'] - df['Age'].mean())/df['Age'].std())
df['Age']

0     -1.779569
1     -0.253270
2     -1.111813
3     -1.016419
4     -1.779569
         ...
395    0.796060
396    1.273028
397    1.177635
398   -0.157877
399    1.082241
Name: Age, Length: 400, dtype: float64

In [ ]:
# min-max scalar